SET(GENERATED_SRC
modules/ugdk-core/src/action/json2spriteanimation.cc
modules/ugdk-core/src/action/mediaplayer.cc
modules/ugdk-core/src/action/scene.cc
modules/ugdk-core/src/audio/manager.cc
modules/ugdk-core/src/audio/module.cc
modules/ugdk-core/src/audio/music.cc
modules/ugdk-core/src/audio/sample.cc
modules/ugdk-core/src/debug/log.cc
modules/ugdk-core/src/debug/profiler.cc
modules/ugdk-core/src/desktop/manager.cc
modules/ugdk-core/src/desktop/module.cc
modules/ugdk-core/src/desktop/window.cc
modules/ugdk-core/src/desktop/windowsettings.cc
modules/ugdk-core/src/filesystem/file.cc
modules/ugdk-core/src/filesystem/manager.cc
modules/ugdk-core/src/filesystem/module.cc
modules/ugdk-core/src/filesystem/sdlfile.cc
modules/ugdk-core/src/filesystem/sdlfile.h
modules/ugdk-core/src/graphic/canvas.cc
modules/ugdk-core/src/graphic/defaultshaders.cc
modules/ugdk-core/src/graphic/drawmode.cc
modules/ugdk-core/src/graphic/gltexture.cc
modules/ugdk-core/src/graphic/gltexture.h
modules/ugdk-core/src/graphic/manager.cc
modules/ugdk-core/src/graphic/module.cc
modules/ugdk-core/src/graphic/rendertarget.cc
modules/ugdk-core/src/graphic/rendertexture.cc
modules/ugdk-core/src/graphic/shader.cc
modules/ugdk-core/src/graphic/shaderprogram.cc
modules/ugdk-core/src/graphic/textureunit.cc
modules/ugdk-core/src/graphic/vertexbuffer.cc
modules/ugdk-core/src/graphic/vertexbuffer.h
modules/ugdk-core/src/graphic/vertexdata.cc
modules/ugdk-core/src/input/joystick.cc
modules/ugdk-core/src/input/joystickstatus.cc
modules/ugdk-core/src/input/keyboard.cc
modules/ugdk-core/src/input/keycode.cc
modules/ugdk-core/src/input/manager.cc
modules/ugdk-core/src/input/module.cc
modules/ugdk-core/src/input/mouse.cc
modules/ugdk-core/src/input/textinput.cc
modules/ugdk-core/src/math/frame.cc
modules/ugdk-core/src/math/integer2D.cc
modules/ugdk-core/src/math/vector2D.cc
modules/ugdk-core/src/pyramidworks/collision/collisionclass.cc
modules/ugdk-core/src/pyramidworks/collision/collisionmanager.cc
modules/ugdk-core/src/pyramidworks/collision/collisionobject.cc
modules/ugdk-core/src/pyramidworks/geometry/circle.cc
modules/ugdk-core/src/pyramidworks/geometry/convexpolygon.cc
modules/ugdk-core/src/pyramidworks/geometry/rect.cc
modules/ugdk-core/src/resource/manager.cc
modules/ugdk-core/src/resource/module.cc
modules/ugdk-core/src/system/configuration.cc
modules/ugdk-core/src/system/engine.cc
modules/ugdk-core/src/system/exceptions.cc
modules/ugdk-core/src/system/sdleventhandler.h
modules/ugdk-core/src/system/taskplayer.cc
modules/ugdk-core/src/time/manager.cc
modules/ugdk-core/src/time/module.cc
modules/ugdk-core/src/time/timeaccumulator.cc
modules/ugdk-core/src/util/idgenerator.cc
modules/ugdk-core/src/util/utf8.cc
)
SET(GENERATED_HEADERS
modules/ugdk-core/include/pyramidworks/collision/collisionclass.h
modules/ugdk-core/include/pyramidworks/collision/collisiondata.h
modules/ugdk-core/include/pyramidworks/collision/collisionmanager.h
modules/ugdk-core/include/pyramidworks/collision/collisionobject.h
modules/ugdk-core/include/pyramidworks/collision.h
modules/ugdk-core/include/pyramidworks/geometry/circle.h
modules/ugdk-core/include/pyramidworks/geometry/convexpolygon.h
modules/ugdk-core/include/pyramidworks/geometry/geometricshape.h
modules/ugdk-core/include/pyramidworks/geometry.h
modules/ugdk-core/include/pyramidworks/geometry/rect.h
modules/ugdk-core/include/ugdk/action/animation.h
modules/ugdk-core/include/ugdk/action/animationplayer.h
modules/ugdk-core/include/ugdk/action/events.h
modules/ugdk-core/include/ugdk/action.h
modules/ugdk-core/include/ugdk/action/json2spriteanimation.h
modules/ugdk-core/include/ugdk/action/mediamanager.h
modules/ugdk-core/include/ugdk/action/mediaplayer.h
modules/ugdk-core/include/ugdk/action/scene.h
modules/ugdk-core/include/ugdk/action/spriteanimationframe.h
modules/ugdk-core/include/ugdk/audio.h
modules/ugdk-core/include/ugdk/audio/manager.h
modules/ugdk-core/include/ugdk/audio/module.h
modules/ugdk-core/include/ugdk/audio/music.h
modules/ugdk-core/include/ugdk/audio/sample.h
modules/ugdk-core/include/ugdk/debug.h
modules/ugdk-core/include/ugdk/debug/log.h
modules/ugdk-core/include/ugdk/debug/profiler.h
modules/ugdk-core/include/ugdk/desktop.h
modules/ugdk-core/include/ugdk/desktop/manager.h
modules/ugdk-core/include/ugdk/desktop/module.h
modules/ugdk-core/include/ugdk/desktop/window.h
modules/ugdk-core/include/ugdk/desktop/windowsettings.h
modules/ugdk-core/include/ugdk/filesystem/file.h
modules/ugdk-core/include/ugdk/filesystem.h
modules/ugdk-core/include/ugdk/filesystem/manager.h
modules/ugdk-core/include/ugdk/filesystem/module.h
modules/ugdk-core/include/ugdk/graphic/canvas.h
modules/ugdk-core/include/ugdk/graphic/defaultshaders.h
modules/ugdk-core/include/ugdk/graphic/drawmode.h
modules/ugdk-core/include/ugdk/graphic/exceptions.h
modules/ugdk-core/include/ugdk/graphic.h
modules/ugdk-core/include/ugdk/graphic/manager.h
modules/ugdk-core/include/ugdk/graphic/module.h
modules/ugdk-core/include/ugdk/graphic/opengl.h
modules/ugdk-core/include/ugdk/graphic/renderer.h
modules/ugdk-core/include/ugdk/graphic/rendertarget.h
modules/ugdk-core/include/ugdk/graphic/rendertexture.h
modules/ugdk-core/include/ugdk/graphic/shader.h
modules/ugdk-core/include/ugdk/graphic/shaderprogram.h
modules/ugdk-core/include/ugdk/graphic/textureatlas.h
modules/ugdk-core/include/ugdk/graphic/textureunit.h
modules/ugdk-core/include/ugdk/graphic/vertexdata.h
modules/ugdk-core/include/ugdk/input/events.h
modules/ugdk-core/include/ugdk/input.h
modules/ugdk-core/include/ugdk/input/joystick.h
modules/ugdk-core/include/ugdk/input/joystickstatus.h
modules/ugdk-core/include/ugdk/input/keyboard.h
modules/ugdk-core/include/ugdk/input/keycode.h
modules/ugdk-core/include/ugdk/input/manager.h
modules/ugdk-core/include/ugdk/input/module.h
modules/ugdk-core/include/ugdk/input/mousebutton.h
modules/ugdk-core/include/ugdk/input/mouse.h
modules/ugdk-core/include/ugdk/input/scancode.h
modules/ugdk-core/include/ugdk/input/textinput.h
modules/ugdk-core/include/ugdk/math/frame.h
modules/ugdk-core/include/ugdk/math/geometry.h
modules/ugdk-core/include/ugdk/math.h
modules/ugdk-core/include/ugdk/math/integer2D.h
modules/ugdk-core/include/ugdk/math/vector2D.h
modules/ugdk-core/include/ugdk/resource.h
modules/ugdk-core/include/ugdk/resource/manager.h
modules/ugdk-core/include/ugdk/resource/module.h
modules/ugdk-core/include/ugdk/resource/resourcecontainer.h
modules/ugdk-core/include/ugdk/script.h
modules/ugdk-core/include/ugdk/structure/box.h
modules/ugdk-core/include/ugdk/structure/color.h
modules/ugdk-core/include/ugdk/structure.h
modules/ugdk-core/include/ugdk/structure/indexabletable.h
modules/ugdk-core/include/ugdk/structure/intervalkdtree.h
modules/ugdk-core/include/ugdk/structure/types.h
modules/ugdk-core/include/ugdk/structure/vertex.h
modules/ugdk-core/include/ugdk/structure/visualeffect.h
modules/ugdk-core/include/ugdk/system/compatibility.h
modules/ugdk-core/include/ugdk/system/configuration.h
modules/ugdk-core/include/ugdk/system/engine.h
modules/ugdk-core/include/ugdk/system/eventhandler.h
modules/ugdk-core/include/ugdk/system/exceptions.h
modules/ugdk-core/include/ugdk/system.h
modules/ugdk-core/include/ugdk/system/task.h
modules/ugdk-core/include/ugdk/system/taskplayer.h
modules/ugdk-core/include/ugdk/text.h
modules/ugdk-core/include/ugdk/time.h
modules/ugdk-core/include/ugdk/time/manager.h
modules/ugdk-core/include/ugdk/time/module.h
modules/ugdk-core/include/ugdk/time/timeaccumulator.h
modules/ugdk-core/include/ugdk/ui.h
modules/ugdk-core/include/ugdk/util.h
modules/ugdk-core/include/ugdk/util/idgenerator.h
modules/ugdk-core/include/ugdk/util/utf8.h
)
