SET(GENERATED_SRC
modules/ugdk-3d/src/action/camera.cc
modules/ugdk-3d/src/action/component.cc
modules/ugdk-3d/src/action/component/physicsbody.cc
modules/ugdk-3d/src/action/component/simplebody.cc
modules/ugdk-3d/src/action/component/view.cc
modules/ugdk-3d/src/action/element.cc
modules/ugdk-3d/src/action/physics.cc
modules/ugdk-3d/src/action/scene3d.cc
modules/ugdk-3d/src/desktop/manager.cc
modules/ugdk-3d/src/desktop/window.cc
)
SET(GENERATED_HEADERS
modules/ugdk-3d/include/ugdk/action/3D/camera.h
modules/ugdk-3d/include/ugdk/action/3D/component/body.h
modules/ugdk-3d/include/ugdk/action/3D/component.h
modules/ugdk-3d/include/ugdk/action/3D/component/physicsbody.h
modules/ugdk-3d/include/ugdk/action/3D/component/simplebody.h
modules/ugdk-3d/include/ugdk/action/3D/component/view.h
modules/ugdk-3d/include/ugdk/action/3D/element.h
modules/ugdk-3d/include/ugdk/action/3D/physics.h
modules/ugdk-3d/include/ugdk/action/3D/scene3d.h
modules/ugdk-3d/include/ugdk/desktop/3D/manager.h
modules/ugdk-3d/include/ugdk/desktop/3D/window.h
)
