SET(UGDK_LUA_SRC 
modules/ugdk-script/src/languages/lua/basegear.cc
modules/ugdk-script/src/languages/lua/bootstrapgear.cc
modules/ugdk-script/src/languages/lua/datagear.cc
modules/ugdk-script/src/languages/lua/luadata.cc
modules/ugdk-script/src/languages/lua/luamodules.cc
modules/ugdk-script/src/languages/lua/luawrapper.cc
modules/ugdk-script/include/ugdk/script/languages/lua/auxlib.h
modules/ugdk-script/include/ugdk/script/languages/lua/basegear.h
modules/ugdk-script/include/ugdk/script/languages/lua/bootstrapgear.h
modules/ugdk-script/include/ugdk/script/languages/lua/datagear.h
modules/ugdk-script/include/ugdk/script/languages/lua/defs.h
modules/ugdk-script/include/ugdk/script/languages/lua/header.h
modules/ugdk-script/include/ugdk/script/languages/lua/luadata.h
modules/ugdk-script/include/ugdk/script/languages/lua/luawrapper.h
modules/ugdk-script/include/ugdk/script/languages/lua/modules.h
modules/ugdk-script/include/ugdk/script/languages/lua/native/traceback.h
modules/ugdk-script/include/ugdk/script/languages/lua/primitive.h
modules/ugdk-script/include/ugdk/script/languages/lua/state.h
modules/ugdk-script/include/ugdk/script/languages/lua/swigluarun.h
)
