SET(UGDK_PYTHON_SRC 
modules/ugdk-script/src/languages/python/pythondata.cc
modules/ugdk-script/src/languages/python/pythonmodules.cc
modules/ugdk-script/src/languages/python/pythonwrapper.cc
modules/ugdk-script/include/ugdk/script/languages/python/modules.h
modules/ugdk-script/include/ugdk/script/languages/python/pythondata.h
modules/ugdk-script/include/ugdk/script/languages/python/pythonwrapper.h
modules/ugdk-script/include/ugdk/script/languages/python/swigpyrun.h
)
