SET(UGDK-SCRIPT_SRC
modules/ugdk-script/src/initscripts.cc
modules/ugdk-script/src/scriptmanager.cc
modules/ugdk-script/src/virtualobj.cc
)
SET(UGDK-SCRIPT_HEADERS
modules/ugdk-script/include/ugdk/script/baseproxy.h
modules/ugdk-script/include/ugdk/script/defs.h
modules/ugdk-script/include/ugdk/script/langwrapper.h
modules/ugdk-script/include/ugdk/script/module.h
modules/ugdk-script/include/ugdk/script/scriptmanager.h
modules/ugdk-script/include/ugdk/script/type.h
modules/ugdk-script/include/ugdk/script/virtualdata.h
modules/ugdk-script/include/ugdk/script/virtualobj.h
modules/ugdk-script/include/ugdk/script/virtualprimitive.h
)
