SET(GENERATED_SRC
modules/ugdk-2d/src/desktop/manager.cc
modules/ugdk-2d/src/desktop/window.cc
modules/ugdk-2d/src/graphic/immediate.cc
modules/ugdk-2d/src/graphic/light.cc
modules/ugdk-2d/src/graphic/pixelsurface.cc
modules/ugdk-2d/src/graphic/pixelsurface.h
modules/ugdk-2d/src/graphic/primitive.cc
modules/ugdk-2d/src/graphic/primitivecontroller.cc
modules/ugdk-2d/src/graphic/primitivesetup.cc
modules/ugdk-2d/src/graphic/sprite.cc
modules/ugdk-2d/src/graphic/textureatlas.cc
modules/ugdk-2d/src/text/font.cc
modules/ugdk-2d/src/text/functions.cc
modules/ugdk-2d/src/text/label.cc
modules/ugdk-2d/src/text/language.cc
modules/ugdk-2d/src/text/languageword.cc
modules/ugdk-2d/src/text/manager.cc
modules/ugdk-2d/src/text/module.cc
modules/ugdk-2d/src/text/textbox.cc
modules/ugdk-2d/src/ui/button.cc
modules/ugdk-2d/src/ui/drawable/primitive.cc
modules/ugdk-2d/src/ui/drawable/texturedrectangle.cc
modules/ugdk-2d/src/ui/menu.cc
modules/ugdk-2d/src/ui/node.cc
modules/ugdk-2d/src/ui/uielement.cc
)
SET(GENERATED_HEADERS
modules/ugdk-2d/include/ugdk/desktop/2D/manager.h
modules/ugdk-2d/include/ugdk/desktop/2D/window.h
modules/ugdk-2d/include/ugdk/graphic/immediate.h
modules/ugdk-2d/include/ugdk/graphic/light.h
modules/ugdk-2d/include/ugdk/graphic/primitivecontroller.h
modules/ugdk-2d/include/ugdk/graphic/primitive.h
modules/ugdk-2d/include/ugdk/graphic/primitivesetup.h
modules/ugdk-2d/include/ugdk/graphic/renderer2D.h
modules/ugdk-2d/include/ugdk/graphic/sprite.h
modules/ugdk-2d/include/ugdk/text/font.h
modules/ugdk-2d/include/ugdk/text/functions.h
modules/ugdk-2d/include/ugdk/text/label.h
modules/ugdk-2d/include/ugdk/text/language.h
modules/ugdk-2d/include/ugdk/text/languageword.h
modules/ugdk-2d/include/ugdk/text/manager.h
modules/ugdk-2d/include/ugdk/text/module.h
modules/ugdk-2d/include/ugdk/text/textbox.h
modules/ugdk-2d/include/ugdk/ui/button.h
modules/ugdk-2d/include/ugdk/ui/drawable.h
modules/ugdk-2d/include/ugdk/ui/drawable/primitive.h
modules/ugdk-2d/include/ugdk/ui/drawable/texturedrectangle.h
modules/ugdk-2d/include/ugdk/ui/hookpoint.h
modules/ugdk-2d/include/ugdk/ui/menu.h
modules/ugdk-2d/include/ugdk/ui/node.h
modules/ugdk-2d/include/ugdk/ui/uielement.h
)
