SET(UGDK_2D_SRC 
include/ugdk/graphic/canvas.h
include/ugdk/graphic/defaultshaders.h
include/ugdk/graphic/drawmode.h
include/ugdk/graphic/exceptions.h
include/ugdk/graphic/geometry.h
include/ugdk/graphic/image.h
include/ugdk/graphic/light.h
include/ugdk/graphic/manager.h
include/ugdk/graphic/module.h
include/ugdk/graphic/opengl/shader.h
include/ugdk/graphic/opengl/shaderprogram.h
include/ugdk/graphic/opengl/vertexbuffer.h
include/ugdk/graphic/primitive.h
include/ugdk/graphic/primitivecontroller.h
include/ugdk/graphic/primitivesetup.h
include/ugdk/graphic/rendertarget.h
include/ugdk/graphic/rendertexture.h
include/ugdk/graphic/sprite.h
include/ugdk/graphic/textureatlas.h
include/ugdk/graphic/textureunit.h
include/ugdk/graphic/vertexdata.h
include/ugdk/graphic/visualeffect.h
include/ugdk/internal/gltexture.h
include/ugdk/internal/opengl.h
include/ugdk/internal/pixelsurface.h
include/ugdk/internal/sdleventhandler.h
include/ugdk/text/font.h
include/ugdk/text/functions.h
include/ugdk/text/label.h
include/ugdk/text/language.h
include/ugdk/text/languageword.h
include/ugdk/text/manager.h
include/ugdk/text/module.h
include/ugdk/text/textbox.h
include/ugdk/ui/button.h
include/ugdk/ui/drawable.h
include/ugdk/ui/drawable/primitive.h
include/ugdk/ui/drawable/texturedrectangle.h
include/ugdk/ui/hookpoint.h
include/ugdk/ui/menu.h
include/ugdk/ui/node.h
include/ugdk/ui/uielement.h
include/ugdk/desktop/2D/manager.h
include/ugdk/desktop/2D/window.h
src/ugdk-2d
src/ugdk-2d/desktop
src/ugdk-2d/desktop/manager.cc
src/ugdk-2d/desktop/window.cc
src/ugdk-2d/graphic
src/ugdk-2d/graphic/canvas.cc
src/ugdk-2d/graphic/defaultshaders.cc
src/ugdk-2d/graphic/drawmode.cc
src/ugdk-2d/graphic/image.cc
src/ugdk-2d/graphic/light.cc
src/ugdk-2d/graphic/manager.cc
src/ugdk-2d/graphic/module.cc
src/ugdk-2d/graphic/opengl
src/ugdk-2d/graphic/opengl/shader.cc
src/ugdk-2d/graphic/opengl/shaderprogram.cc
src/ugdk-2d/graphic/opengl/vertexbuffer.cc
src/ugdk-2d/graphic/primitive.cc
src/ugdk-2d/graphic/primitivecontroller.cc
src/ugdk-2d/graphic/primitivesetup.cc
src/ugdk-2d/graphic/rendertarget.cc
src/ugdk-2d/graphic/rendertexture.cc
src/ugdk-2d/graphic/sprite.cc
src/ugdk-2d/graphic/textureatlas.cc
src/ugdk-2d/graphic/textureunit.cc
src/ugdk-2d/graphic/vertexdata.cc
src/ugdk-2d/internal
src/ugdk-2d/internal/gltexture.cc
src/ugdk-2d/internal/pixelsurface.cc
src/ugdk-2d/text
src/ugdk-2d/text/font.cc
src/ugdk-2d/text/functions.cc
src/ugdk-2d/text/label.cc
src/ugdk-2d/text/language.cc
src/ugdk-2d/text/languageword.cc
src/ugdk-2d/text/manager.cc
src/ugdk-2d/text/module.cc
src/ugdk-2d/text/textbox.cc
src/ugdk-2d/ui
src/ugdk-2d/ui/button.cc
src/ugdk-2d/ui/drawable
src/ugdk-2d/ui/drawable/primitive.cc
src/ugdk-2d/ui/drawable/texturedrectangle.cc
src/ugdk-2d/ui/menu.cc
src/ugdk-2d/ui/node.cc
src/ugdk-2d/ui/uielement.cc
)
