SET(UGDK_2D_SRC 
headers/ugdk-2d/ugdk/desktop/2D/manager.h
headers/ugdk-2d/ugdk/desktop/2D/window.h
headers/ugdk-2d/ugdk/graphic/canvas.h
headers/ugdk-2d/ugdk/graphic/defaultshaders.h
headers/ugdk-2d/ugdk/graphic/drawmode.h
headers/ugdk-2d/ugdk/graphic/exceptions.h
headers/ugdk-2d/ugdk/graphic/geometry.h
headers/ugdk-2d/ugdk/graphic/image.h
headers/ugdk-2d/ugdk/graphic/light.h
headers/ugdk-2d/ugdk/graphic/manager.h
headers/ugdk-2d/ugdk/graphic/module.h
headers/ugdk-2d/ugdk/graphic/opengl/shader.h
headers/ugdk-2d/ugdk/graphic/opengl/shaderprogram.h
headers/ugdk-2d/ugdk/graphic/opengl/vertexbuffer.h
headers/ugdk-2d/ugdk/graphic/primitive.h
headers/ugdk-2d/ugdk/graphic/primitivecontroller.h
headers/ugdk-2d/ugdk/graphic/primitivesetup.h
headers/ugdk-2d/ugdk/graphic/rendertarget.h
headers/ugdk-2d/ugdk/graphic/rendertexture.h
headers/ugdk-2d/ugdk/graphic/sprite.h
headers/ugdk-2d/ugdk/graphic/spriteanimationframe.h
headers/ugdk-2d/ugdk/graphic/spritetypes.h
headers/ugdk-2d/ugdk/graphic/textureatlas.h
headers/ugdk-2d/ugdk/graphic/textureunit.h
headers/ugdk-2d/ugdk/graphic/vertexdata.h
headers/ugdk-2d/ugdk/graphic/visualeffect.h
headers/ugdk-2d/ugdk/internal/gltexture.h
headers/ugdk-2d/ugdk/internal/opengl.h
headers/ugdk-2d/ugdk/internal/pixelsurface.h
headers/ugdk-2d/ugdk/text/font.h
headers/ugdk-2d/ugdk/text/functions.h
headers/ugdk-2d/ugdk/text/label.h
headers/ugdk-2d/ugdk/text/language.h
headers/ugdk-2d/ugdk/text/languageword.h
headers/ugdk-2d/ugdk/text/manager.h
headers/ugdk-2d/ugdk/text/module.h
headers/ugdk-2d/ugdk/text/textbox.h
headers/ugdk-2d/ugdk/ui/button.h
headers/ugdk-2d/ugdk/ui/drawable.h
headers/ugdk-2d/ugdk/ui/drawable/primitive.h
headers/ugdk-2d/ugdk/ui/drawable/texturedrectangle.h
headers/ugdk-2d/ugdk/ui/hookpoint.h
headers/ugdk-2d/ugdk/ui/menu.h
headers/ugdk-2d/ugdk/ui/node.h
headers/ugdk-2d/ugdk/ui/uielement.h
src/ugdk-2d/desktop/manager.cc
src/ugdk-2d/desktop/window.cc
src/ugdk-2d/graphic/canvas.cc
src/ugdk-2d/graphic/defaultshaders.cc
src/ugdk-2d/graphic/drawmode.cc
src/ugdk-2d/graphic/image.cc
src/ugdk-2d/graphic/light.cc
src/ugdk-2d/graphic/manager.cc
src/ugdk-2d/graphic/module.cc
src/ugdk-2d/graphic/opengl/shader.cc
src/ugdk-2d/graphic/opengl/shaderprogram.cc
src/ugdk-2d/graphic/opengl/vertexbuffer.cc
src/ugdk-2d/graphic/primitive.cc
src/ugdk-2d/graphic/primitivecontroller.cc
src/ugdk-2d/graphic/primitivesetup.cc
src/ugdk-2d/graphic/rendertarget.cc
src/ugdk-2d/graphic/rendertexture.cc
src/ugdk-2d/graphic/sprite.cc
src/ugdk-2d/graphic/spritetypes.cc
src/ugdk-2d/graphic/textureatlas.cc
src/ugdk-2d/graphic/textureunit.cc
src/ugdk-2d/graphic/vertexdata.cc
src/ugdk-2d/internal/gltexture.cc
src/ugdk-2d/internal/pixelsurface.cc
src/ugdk-2d/text/font.cc
src/ugdk-2d/text/functions.cc
src/ugdk-2d/text/label.cc
src/ugdk-2d/text/language.cc
src/ugdk-2d/text/languageword.cc
src/ugdk-2d/text/manager.cc
src/ugdk-2d/text/module.cc
src/ugdk-2d/text/textbox.cc
src/ugdk-2d/ui/button.cc
src/ugdk-2d/ui/drawable/primitive.cc
src/ugdk-2d/ui/drawable/texturedrectangle.cc
src/ugdk-2d/ui/menu.cc
src/ugdk-2d/ui/node.cc
src/ugdk-2d/ui/uielement.cc
)
