SET(UGDK_2D_SRC 
src/ugdk/graphic/canvas.cc
src/ugdk/graphic/canvas.h
src/ugdk/graphic/defaultshaders.cc
src/ugdk/graphic/defaultshaders.h
src/ugdk/graphic/drawmode.cc
src/ugdk/graphic/drawmode.h
src/ugdk/graphic/exceptions.h
src/ugdk/graphic/geometry.h
src/ugdk/graphic/image.cc
src/ugdk/graphic/image.h
src/ugdk/graphic/light.cc
src/ugdk/graphic/light.h
src/ugdk/graphic/manager.cc
src/ugdk/graphic/manager.h
src/ugdk/graphic/module.cc
src/ugdk/graphic/module.h
src/ugdk/graphic/opengl/shader.cc
src/ugdk/graphic/opengl/shader.h
src/ugdk/graphic/opengl/shaderprogram.cc
src/ugdk/graphic/opengl/shaderprogram.h
src/ugdk/graphic/opengl/vertexbuffer.cc
src/ugdk/graphic/opengl/vertexbuffer.h
src/ugdk/graphic/primitive.cc
src/ugdk/graphic/primitivecontroller.cc
src/ugdk/graphic/primitivecontroller.h
src/ugdk/graphic/primitive.h
src/ugdk/graphic/primitivesetup.cc
src/ugdk/graphic/primitivesetup.h
src/ugdk/graphic/rendertarget.cc
src/ugdk/graphic/rendertarget.h
src/ugdk/graphic/rendertexture.cc
src/ugdk/graphic/rendertexture.h
src/ugdk/graphic/sprite.cc
src/ugdk/graphic/sprite.h
src/ugdk/graphic/textureatlas.cc
src/ugdk/graphic/textureatlas.h
src/ugdk/graphic/textureunit.cc
src/ugdk/graphic/textureunit.h
src/ugdk/graphic/vertexdata.cc
src/ugdk/graphic/vertexdata.h
src/ugdk/graphic/visualeffect.h
src/ugdk/internal/gltexture.cc
src/ugdk/internal/gltexture.h
src/ugdk/internal/opengl.h
src/ugdk/internal/pixelsurface.cc
src/ugdk/internal/pixelsurface.h
src/ugdk/internal/sdleventhandler.h
src/ugdk/text/font.cc
src/ugdk/text/font.h
src/ugdk/text/functions.cc
src/ugdk/text/functions.h
src/ugdk/text/label.cc
src/ugdk/text/label.h
src/ugdk/text/language.cc
src/ugdk/text/language.h
src/ugdk/text/languageword.cc
src/ugdk/text/languageword.h
src/ugdk/text/manager.cc
src/ugdk/text/manager.h
src/ugdk/text/module.cc
src/ugdk/text/module.h
src/ugdk/text/textbox.cc
src/ugdk/text/textbox.h
src/ugdk/ui/button.cc
src/ugdk/ui/button.h
src/ugdk/ui/drawable.h
src/ugdk/ui/drawable/primitive.cc
src/ugdk/ui/drawable/primitive.h
src/ugdk/ui/drawable/texturedrectangle.cc
src/ugdk/ui/drawable/texturedrectangle.h
src/ugdk/ui/hookpoint.h
src/ugdk/ui/menu.cc
src/ugdk/ui/menu.h
src/ugdk/ui/node.cc
src/ugdk/ui/node.h
src/ugdk/ui/uielement.cc
src/ugdk/ui/uielement.h
src/ugdk/desktop/2D/manager.cc
src/ugdk/desktop/2D/manager.h
src/ugdk/desktop/2D/window.cc
src/ugdk/desktop/2D/window.h
)
