SET(UGDK_3D_SRC 
headers/ugdk-3d/bulletworks/manager.h
headers/ugdk-3d/bulletworks/object.h
headers/ugdk-3d/bulletworks/physicscene.h
headers/ugdk-3d/ugdk/action/3D/camera.h
headers/ugdk-3d/ugdk/action/3D/ogreentity.h
headers/ugdk-3d/ugdk/action/3D/ogrescene.h
headers/ugdk-3d/ugdk/desktop/3D/manager.h
headers/ugdk-3d/ugdk/desktop/3D/window.h
src/ugdk-3d/action/camera.cc
src/ugdk-3d/action/ogreentity.cc
src/ugdk-3d/action/ogrescene.cc
src/ugdk-3d/bulletworks/manager.cc
src/ugdk-3d/bulletworks/object.cc
src/ugdk-3d/bulletworks/physicscene.cc
src/ugdk-3d/desktop/manager.cc
src/ugdk-3d/desktop/window.cc
)
