SET(UGDK_3D_SRC 
include/ugdk/action/3D/camera.h
include/ugdk/action/3D/ogreentity.h
include/ugdk/action/3D/ogrescene.h
include/ugdk/desktop/3D/manager.h
include/ugdk/desktop/3D/window.h
src/ugdk/action/3D/camera.cc
src/ugdk/action/3D/ogreentity.cc
src/ugdk/action/3D/ogrescene.cc
src/ugdk/desktop/3D/manager.cc
src/ugdk/desktop/3D/window.cc
include/bulletworks/manager.h
include/bulletworks/object.h
include/bulletworks/physicscene.h
src/bulletworks/manager.cc
src/bulletworks/object.cc
src/bulletworks/physicscene.cc
)
