SET(UGDK_3D_SRC 
include/ugdk/action/3D/camera.h
include/ugdk/action/3D/ogreentity.h
include/ugdk/action/3D/ogrescene.h
include/ugdk/desktop/3D/manager.h
include/ugdk/desktop/3D/window.h
include/bulletworks/manager.h
include/bulletworks/object.h
include/bulletworks/physicscene.h
src/ugdk-3d/action/camera.cc
src/ugdk-3d/action/ogreentity.cc
src/ugdk-3d/action/ogrescene.cc
src/ugdk-3d/bulletworks/manager.cc
src/ugdk-3d/bulletworks/object.cc
src/ugdk-3d/bulletworks/physicscene.cc
src/ugdk-3d/desktop/manager.cc
src/ugdk-3d/desktop/window.cc
)
