SET(UGDK_LUA_SRC 
include/ugdk/script/languages/lua/auxlib.h
include/ugdk/script/languages/lua/basegear.h
include/ugdk/script/languages/lua/bootstrapgear.h
include/ugdk/script/languages/lua/datagear.h
include/ugdk/script/languages/lua/defs.h
include/ugdk/script/languages/lua/header.h
include/ugdk/script/languages/lua/luadata.h
include/ugdk/script/languages/lua/luawrapper.h
include/ugdk/script/languages/lua/modules.h
include/ugdk/script/languages/lua/native/traceback.h
include/ugdk/script/languages/lua/primitive.h
include/ugdk/script/languages/lua/state.h
include/ugdk/script/languages/lua/swigluarun.h
src/ugdk-script/languages/lua/basegear.cc
src/ugdk-script/languages/lua/bootstrapgear.cc
src/ugdk-script/languages/lua/datagear.cc
src/ugdk-script/languages/lua/luadata.cc
src/ugdk-script/languages/lua/luamodules.cc
src/ugdk-script/languages/lua/luawrapper.cc
)
