SET(UGDK_PYTHON_SRC 
headers/ugdk-core/ugdk/script/languages/python/modules.h
headers/ugdk-core/ugdk/script/languages/python/pythondata.h
headers/ugdk-core/ugdk/script/languages/python/pythonwrapper.h
headers/ugdk-core/ugdk/script/languages/python/swigpyrun.h
src/ugdk-script/languages/python/pythondata.cc
src/ugdk-script/languages/python/pythonmodules.cc
src/ugdk-script/languages/python/pythonwrapper.cc
)
