SET(UGDK_PYTHON_SRC 
    src/ugdk/script/languages/python/modules.h 
    src/ugdk/script/languages/python/pythondata.cc 
    src/ugdk/script/languages/python/pythondata.h 
    src/ugdk/script/languages/python/pythonmodules.cc 
    src/ugdk/script/languages/python/pythonwrapper.cc 
    src/ugdk/script/languages/python/pythonwrapper.h 
    src/ugdk/script/languages/python/swigpyrun.h 
)
