SET(UGDK_PYTHON_SRC 
include/ugdk/script/languages/python/modules.h
include/ugdk/script/languages/python/pythondata.h
include/ugdk/script/languages/python/pythonwrapper.h
include/ugdk/script/languages/python/swigpyrun.h
src/ugdk/script/languages/python/pythondata.cc
src/ugdk/script/languages/python/pythonmodules.cc
src/ugdk/script/languages/python/pythonwrapper.cc
)
