set (FRAMEWORK_SRC
    ${SRC_DIR}/kits/pyramidworks/collision.h
    ${SRC_DIR}/kits/pyramidworks/geometry.h
    ${SRC_DIR}/kits/pyramidworks/collision/collisionclass.cc
    ${SRC_DIR}/kits/pyramidworks/collision/collisionclass.h
    ${SRC_DIR}/kits/pyramidworks/collision/collisionlogic.h
    ${SRC_DIR}/kits/pyramidworks/collision/collisionmanager.cc
    ${SRC_DIR}/kits/pyramidworks/collision/collisionmanager.h
    ${SRC_DIR}/kits/pyramidworks/collision/collisionobject.cc
    ${SRC_DIR}/kits/pyramidworks/collision/collisionobject.h
    ${SRC_DIR}/kits/pyramidworks/geometry/circle.cc
    ${SRC_DIR}/kits/pyramidworks/geometry/circle.h
    ${SRC_DIR}/kits/pyramidworks/geometry/geometricshape.h
    ${SRC_DIR}/kits/pyramidworks/geometry/rect.cc
    ${SRC_DIR}/kits/pyramidworks/geometry/rect.h
    ${SRC_DIR}/ugdk/action.h
    ${SRC_DIR}/ugdk/audio.h
    ${SRC_DIR}/ugdk/graphic.h
    ${SRC_DIR}/ugdk/input.h
    ${SRC_DIR}/ugdk/time.h
    ${SRC_DIR}/ugdk/util.h
    ${SRC_DIR}/ugdk/action/animation.cc
    ${SRC_DIR}/ugdk/action/animation.h
    ${SRC_DIR}/ugdk/action/animationset.cc
    ${SRC_DIR}/ugdk/action/animationset.h
    ${SRC_DIR}/ugdk/action/entity.h
    ${SRC_DIR}/ugdk/action/observer.h
    ${SRC_DIR}/ugdk/action/scene.cc
    ${SRC_DIR}/ugdk/action/scene.h
    ${SRC_DIR}/ugdk/audio/audiomanager.cc
    ${SRC_DIR}/ugdk/audio/audiomanager.h
    ${SRC_DIR}/ugdk/audio/music.cc
    ${SRC_DIR}/ugdk/audio/music.h
    ${SRC_DIR}/ugdk/audio/sample.cc
    ${SRC_DIR}/ugdk/audio/sample.h
    ${SRC_DIR}/ugdk/base/engine.cc
    ${SRC_DIR}/ugdk/base/engine.h
    ${SRC_DIR}/ugdk/base/resourcecontainer.h
    ${SRC_DIR}/ugdk/base/resourcemanager.cc
    ${SRC_DIR}/ugdk/base/resourcemanager.h
    ${SRC_DIR}/ugdk/base/texturecontainer.cc
    ${SRC_DIR}/ugdk/base/texturecontainer.h
    ${SRC_DIR}/ugdk/base/types.h
    ${SRC_DIR}/ugdk/config/config.h
    ${SRC_DIR}/ugdk/graphic/drawable.h
    ${SRC_DIR}/ugdk/graphic/font.cc
    ${SRC_DIR}/ugdk/graphic/font.h
    ${SRC_DIR}/ugdk/graphic/light.cc
    ${SRC_DIR}/ugdk/graphic/light.h
    ${SRC_DIR}/ugdk/graphic/modifier.cc
    ${SRC_DIR}/ugdk/graphic/modifier.h
    ${SRC_DIR}/ugdk/graphic/node.cc
    ${SRC_DIR}/ugdk/graphic/node.h
    ${SRC_DIR}/ugdk/graphic/spritesheet.h
    ${SRC_DIR}/ugdk/graphic/textmanager.cc
    ${SRC_DIR}/ugdk/graphic/textmanager.h
    ${SRC_DIR}/ugdk/graphic/texture.cc
    ${SRC_DIR}/ugdk/graphic/texture.h
    ${SRC_DIR}/ugdk/graphic/videomanager.cc
    ${SRC_DIR}/ugdk/graphic/videomanager.h
    ${SRC_DIR}/ugdk/graphic/drawable/shape.h
    ${SRC_DIR}/ugdk/graphic/drawable/solidrectangle.cc
    ${SRC_DIR}/ugdk/graphic/drawable/solidrectangle.h
    ${SRC_DIR}/ugdk/graphic/drawable/sprite.cc
    ${SRC_DIR}/ugdk/graphic/drawable/sprite.h
    ${SRC_DIR}/ugdk/graphic/drawable/text.cc
    ${SRC_DIR}/ugdk/graphic/drawable/text.h
    ${SRC_DIR}/ugdk/graphic/drawable/texturedrectangle.cc
    ${SRC_DIR}/ugdk/graphic/drawable/texturedrectangle.h
    ${SRC_DIR}/ugdk/graphic/spritesheet/fixedspritesheet.cc
    ${SRC_DIR}/ugdk/graphic/spritesheet/fixedspritesheet.h
    ${SRC_DIR}/ugdk/graphic/spritesheet/flexiblespritesheet.cc
    ${SRC_DIR}/ugdk/graphic/spritesheet/flexiblespritesheet.h
    ${SRC_DIR}/ugdk/input/inputmanager.cc
    ${SRC_DIR}/ugdk/input/inputmanager.h
    ${SRC_DIR}/ugdk/input/keys.h
    ${SRC_DIR}/ugdk/math/frame.cc
    ${SRC_DIR}/ugdk/math/frame.h
    ${SRC_DIR}/ugdk/math/vector2D.cc
    ${SRC_DIR}/ugdk/math/vector2D.h
    ${SRC_DIR}/ugdk/time/timeaccumulator.cc
    ${SRC_DIR}/ugdk/time/timeaccumulator.h
    ${SRC_DIR}/ugdk/time/timemanager.cc
    ${SRC_DIR}/ugdk/time/timemanager.h
    ${SRC_DIR}/ugdk/util/animationparser.cc
    ${SRC_DIR}/ugdk/util/animationparser.h
    ${SRC_DIR}/ugdk/util/animationprotocol.cc
    ${SRC_DIR}/ugdk/util/animationprotocol.h
    ${SRC_DIR}/ugdk/util/intervalkdtree.h
    ${SRC_DIR}/ugdk/util/language.cc
    ${SRC_DIR}/ugdk/util/language.h
    ${SRC_DIR}/ugdk/util/languagemanager.cc
    ${SRC_DIR}/ugdk/util/languagemanager.h
    ${SRC_DIR}/ugdk/util/languageword.h
    ${SRC_DIR}/ugdk/util/pathmanager.cc
    ${SRC_DIR}/ugdk/util/pathmanager.h
    ${SRC_DIR}/ugdk/util/utf8.cc
    ${SRC_DIR}/ugdk/util/utf8.h
    ${SRC_DIR}/ugdk/util/gdd/abstractloader.h
    ${SRC_DIR}/ugdk/util/gdd/cachedloader.h
    ${SRC_DIR}/ugdk/util/gdd/descriptionprotocol.h
    ${SRC_DIR}/ugdk/util/gdd/parser.h
    ${SRC_DIR}/ugdk/util/gdd/parserutility.h
    ${SRC_DIR}/ugdk/util/gdd/reader.cc
    ${SRC_DIR}/ugdk/util/gdd/reader.h
    ${SRC_DIR}/ugdk/util/gdd/simpleloader.h
)
