SET(UGDK_SRC 
include/pyramidworks/collision.h
include/pyramidworks/collision/collisionclass.h
include/pyramidworks/collision/collisiondata.h
include/pyramidworks/collision/collisionmanager.h
include/pyramidworks/collision/collisionobject.h
include/pyramidworks/geometry.h
include/pyramidworks/geometry/circle.h
include/pyramidworks/geometry/convexpolygon.h
include/pyramidworks/geometry/geometricshape.h
include/pyramidworks/geometry/rect.h
include/ugdk/action.h
include/ugdk/action/animationplayer.h
include/ugdk/action/events.h
include/ugdk/action/mediamanager.h
include/ugdk/action/mediaplayer.h
include/ugdk/action/observer.h
include/ugdk/action/scene.h
include/ugdk/action/spriteanimationframe.h
include/ugdk/action/spritetypes.h
include/ugdk/audio.h
include/ugdk/audio/manager.h
include/ugdk/audio/module.h
include/ugdk/audio/music.h
include/ugdk/audio/sample.h
include/ugdk/debug.h
include/ugdk/debug/log.h
include/ugdk/debug/profiler.h
include/ugdk/desktop.h
include/ugdk/desktop/manager.h
include/ugdk/desktop/module.h
include/ugdk/desktop/window.h
include/ugdk/desktop/windowsettings.h
include/ugdk/graphic.h
include/ugdk/input.h
include/ugdk/input/events.h
include/ugdk/input/keyboard.h
include/ugdk/input/keycode.h
include/ugdk/input/manager.h
include/ugdk/input/module.h
include/ugdk/input/mouse.h
include/ugdk/input/mousebutton.h
include/ugdk/input/scancode.h
include/ugdk/input/textinput.h
include/ugdk/internal.h
include/ugdk/math.h
include/ugdk/math/frame.h
include/ugdk/math/integer2D.h
include/ugdk/math/vector2D.h
include/ugdk/resource.h
include/ugdk/resource/genericcontainer.h
include/ugdk/resource/manager.h
include/ugdk/resource/module.h
include/ugdk/resource/resourcecontainer.h
include/ugdk/script.h
include/ugdk/script/baseproxy.h
include/ugdk/script/defs.h
include/ugdk/script/langwrapper.h
include/ugdk/script/module.h
include/ugdk/script/scriptmanager.h
include/ugdk/script/type.h
include/ugdk/script/virtualdata.h
include/ugdk/script/virtualobj.h
include/ugdk/script/virtualprimitive.h
include/ugdk/structure.h
include/ugdk/structure/box.h
include/ugdk/structure/indexabletable.h
include/ugdk/structure/intervalkdtree.h
include/ugdk/structure/types.h
include/ugdk/system.h
include/ugdk/system/compatibility.h
include/ugdk/system/configuration.h
include/ugdk/system/engine.h
include/ugdk/system/eventhandler.h
include/ugdk/system/exceptions.h
include/ugdk/system/LoveException.h
include/ugdk/system/task.h
include/ugdk/system/taskplayer.h
include/ugdk/text.h
include/ugdk/time.h
include/ugdk/time/manager.h
include/ugdk/time/module.h
include/ugdk/time/timeaccumulator.h
include/ugdk/ui.h
include/ugdk/util.h
include/ugdk/util/idgenerator.h
include/ugdk/util/uncopyable.h
include/ugdk/util/utf8.h
src/ugdk-core
src/ugdk-core/action
src/ugdk-core/action/mediaplayer.cc
src/ugdk-core/action/scene.cc
src/ugdk-core/action/spritetypes.cc
src/ugdk-core/audio
src/ugdk-core/audio/manager.cc
src/ugdk-core/audio/module.cc
src/ugdk-core/audio/music.cc
src/ugdk-core/audio/sample.cc
src/ugdk-core/debug
src/ugdk-core/debug/log.cc
src/ugdk-core/debug/profiler.cc
src/ugdk-core/desktop
src/ugdk-core/desktop/manager.cc
src/ugdk-core/desktop/module.cc
src/ugdk-core/desktop/windowsettings.cc
src/ugdk-core/input
src/ugdk-core/input/keyboard.cc
src/ugdk-core/input/keycode.cc
src/ugdk-core/input/manager.cc
src/ugdk-core/input/module.cc
src/ugdk-core/input/mouse.cc
src/ugdk-core/input/textinput.cc
src/ugdk-core/math
src/ugdk-core/math/frame.cc
src/ugdk-core/math/integer2D.cc
src/ugdk-core/math/vector2D.cc
src/ugdk-core/pyramidworks
src/ugdk-core/pyramidworks/collision
src/ugdk-core/pyramidworks/collision/collisionclass.cc
src/ugdk-core/pyramidworks/collision/collisionmanager.cc
src/ugdk-core/pyramidworks/collision/collisionobject.cc
src/ugdk-core/pyramidworks/geometry
src/ugdk-core/pyramidworks/geometry/circle.cc
src/ugdk-core/pyramidworks/geometry/convexpolygon.cc
src/ugdk-core/pyramidworks/geometry/rect.cc
src/ugdk-core/resource
src/ugdk-core/resource/manager.cc
src/ugdk-core/resource/module.cc
src/ugdk-core/system
src/ugdk-core/system/configuration.cc
src/ugdk-core/system/engine.cc
src/ugdk-core/system/LoveException.cc
src/ugdk-core/system/taskplayer.cc
src/ugdk-core/time
src/ugdk-core/time/manager.cc
src/ugdk-core/time/module.cc
src/ugdk-core/time/timeaccumulator.cc
src/ugdk-core/util
src/ugdk-core/util/idgenerator.cc
src/ugdk-core/util/utf8.cc
src/ugdk-script
src/ugdk-script/initscripts.cc
src/ugdk-script/languages
src/ugdk-script/scriptmanager.cc
src/ugdk-script/virtualobj.cc
)
