set (FRAMEWORK_SRC
    ${SRC_DIR}/ugdk/action/animation.cc
    ${SRC_DIR}/ugdk/action/animation.h
    ${SRC_DIR}/ugdk/action/animationset.cc
    ${SRC_DIR}/ugdk/action/animationset.h
    ${SRC_DIR}/ugdk/action/layer.cc
    ${SRC_DIR}/ugdk/action/layer.h
    ${SRC_DIR}/ugdk/action/observer.h
    ${SRC_DIR}/ugdk/action/scene.cc
    ${SRC_DIR}/ugdk/action/scene.h
    ${SRC_DIR}/ugdk/action/sprite.cc
    ${SRC_DIR}/ugdk/action/sprite.h
    ${SRC_DIR}/ugdk/audio/audiomanager.cc
    ${SRC_DIR}/ugdk/audio/audiomanager.h
    ${SRC_DIR}/ugdk/audio/music.cc
    ${SRC_DIR}/ugdk/audio/music.h
    ${SRC_DIR}/ugdk/audio/sample.cc
    ${SRC_DIR}/ugdk/audio/sample.h
    ${SRC_DIR}/ugdk/base/engine.cc
    ${SRC_DIR}/ugdk/base/engine.h
    ${SRC_DIR}/ugdk/base/types.h
    ${SRC_DIR}/ugdk/config/config.h
    ${SRC_DIR}/ugdk/graphic/drawable.h
    ${SRC_DIR}/ugdk/graphic/font.cc
    ${SRC_DIR}/ugdk/graphic/font.h
    ${SRC_DIR}/ugdk/graphic/image.cc
    ${SRC_DIR}/ugdk/graphic/image.h
    ${SRC_DIR}/ugdk/graphic/light.cc
    ${SRC_DIR}/ugdk/graphic/light.h
    ${SRC_DIR}/ugdk/graphic/modifier.cc
    ${SRC_DIR}/ugdk/graphic/modifier.h
    ${SRC_DIR}/ugdk/graphic/text.cc
    ${SRC_DIR}/ugdk/graphic/text.h
    ${SRC_DIR}/ugdk/graphic/textmanager.cc
    ${SRC_DIR}/ugdk/graphic/textmanager.h
    ${SRC_DIR}/ugdk/graphic/videomanager.cc
    ${SRC_DIR}/ugdk/graphic/videomanager.h
    ${SRC_DIR}/ugdk/input/inputmanager.cc
    ${SRC_DIR}/ugdk/input/inputmanager.h
    ${SRC_DIR}/ugdk/input/keys.h
    ${SRC_DIR}/ugdk/math/frame.cc
    ${SRC_DIR}/ugdk/math/frame.h
    ${SRC_DIR}/ugdk/math/vector2D.cc
    ${SRC_DIR}/ugdk/math/vector2D.h
    ${SRC_DIR}/ugdk/time/timeaccumulator.cc
    ${SRC_DIR}/ugdk/time/timeaccumulator.h
    ${SRC_DIR}/ugdk/time/timehandler.cc
    ${SRC_DIR}/ugdk/time/timehandler.h
    ${SRC_DIR}/ugdk/util/animationparser.cc
    ${SRC_DIR}/ugdk/util/animationparser.h
    ${SRC_DIR}/ugdk/util/gamedata.cc
    ${SRC_DIR}/ugdk/util/gamedata.h
    ${SRC_DIR}/ugdk/util/gdd.cc
    ${SRC_DIR}/ugdk/util/pathmanager.cc
    ${SRC_DIR}/ugdk/util/pathmanager.h
    ${SRC_DIR}/ugdk/util/gdd/abstractloader.h
    ${SRC_DIR}/ugdk/util/gdd/cachedloader.h
    ${SRC_DIR}/ugdk/util/gdd/loaderprotocol.h
    ${SRC_DIR}/ugdk/util/gdd/parser.h
    ${SRC_DIR}/ugdk/util/gdd/simpleloader.h
)
