SET(UGDK_MODULE_SRC 
src/module/pyramidworks_collision.i
src/module/pyramidworks_geometry.i
src/module/ugdk_action.i
src/module/ugdk_audio.i
src/module/ugdk_debug.i
src/module/ugdk_input.i
src/module/ugdk_input_keycode.i
src/module/ugdk_input_mousebutton.i
src/module/ugdk_input_scancode.i
src/module/ugdk_internal.i
src/module/ugdk_math.i
src/module/ugdk_resource.i
src/module/ugdk_structure.i
src/module/ugdk_system.i
src/module/ugdk_time.i
src/module/ugdk_util.i
)
