SET(UGDK_MODULE_2D_SRC 
src/module/ugdk_desktop_2D.i
src/module/ugdk_graphic_2D.i
src/module/ugdk_ui_2D.i
)
SET(UGDK_MODULE_2D_SRC 
src/module/ugdk_desktop_2D.i
src/module/ugdk_graphic_2D.i
src/module/ugdk_resource_2D.i
src/module/ugdk_ui_2D.i
)
SET(UGDK_MODULE_2D_SRC 
src/module/ugdk_desktop_2D.i
src/module/ugdk_graphic_2D.i
src/module/ugdk_resource_2D.i
src/module/ugdk_ui_2D.i
)
SET(UGDK_MODULE_2D_SRC 
src/module/ugdk_desktop_2D.i
src/module/ugdk_graphic_2D.i
src/module/ugdk_resource_2D.i
src/module/ugdk_text_2D.i
src/module/ugdk_ui_2D.i
)
SET(UGDK_MODULE_2D_SRC 
src/module/ugdk_desktop_2D.i
src/module/ugdk_graphic_2D.i
src/module/ugdk_resource_2D.i
src/module/ugdk_text_2D.i
src/module/ugdk_ui_2D.i
)
SET(UGDK_MODULE_2D_SRC 
src/module/ugdk_desktop_2D.i
src/module/ugdk_graphic_2D.i
src/module/ugdk_resource_2D.i
src/module/ugdk_text_2D.i
src/module/ugdk_ui_2D.i
)
