SET(UGDK_MODULE_SRC 
    ugdk_action.i 
    ugdk_audio.i 
    ugdk_base.i 
    ugdk_drawable.i 
    ugdk_gdd.i 
    ugdk_graphic.i 
    ugdk_input.i 
    ugdk_math.i 
    ugdk_spritesheet.i 
    ugdk_time.i 
    ugdk_util.i 
)
